# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/MindVault',
                'doc_host': 'https://TensorMages.github.io',
                'git_url': 'https://github.com/TensorMages/MindVault',
                'lib_path': 'MindVault'},
  'syms': {'MindVault.core': {'MindVault.core.foo': ('core.html#foo', 'MindVault/core.py')}}}
